import '../global.css';
import { QueryProvider } from '../components/QueryProvider';
import { Toaster } from '@one-exam-monorepo/ui';

export const metadata = {
  title: 'Welcome to teacher-client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
